// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {diffGitLineTokenizer, preambleTokenizer, diffContentTokenizer} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$OOVQVOOOhQVO'#CpOOQU'#Cq'#CqO!PQTO'#CqOOQU'#Ct'#CtO!_QVO'#CoQ!pQROOOOQU,59[,59[O!uQVO,59[OOQU,59],59]O#ZQTO,59]OOQU-E6r-E6rO#`QZO'#CsOOQQ'#Cu'#CuO#nQRO'#CrQOQPOOOOQU1G.v1G.vO#vQTO1G.wOOQY'#Cv'#CvO#{QZO,59_OOQQ-E6s-E6sOOQU7+$c7+$cOOQY-E6t-E6t",
  stateData: "$Z~OmOS~OQPOTQOUROPcPkcP~ORWOSVOPdXQdXTdXUdXkdX~OVXOWXOXXOYYO~OQPOTQOUROPcXkcX~OP[O~OS`OPdaQdaTdaUdakda~OZaO~O^bOabOPgXkgX~OP[OkfX~O[eO~O^bOabOPgakga~O",
  goto: "!^kPPPPPPPPPPPPPPPPPPPloosvz!Q!WRUOTSOTR_UT]U^QTORZTQ^URd^Qc[Rfc",
  nodeNames: "⚠ DiffGitLine MessageNormal MessageWarn MessageIllegal CommentWhole CommentMarker StatusChanged StatusInserted StatusDeleted FileType CommentColon CommentValue DiffHunkHeader DiffMetaLine DiffAddedLine DiffRemovedLine DiffContextLine Program Preamble MessageLine CommentLine DiffZone DiffBlock",
  maxTerm: 29,
  skippedNodes: [0,13,15,16],
  repeatNodeCount: 3,
  tokenData: "^~RPYZU~ZPm~YZU",
  tokenizers: [0, diffGitLineTokenizer, preambleTokenizer, diffContentTokenizer],
  topRules: {"Program":[0,18]},
  tokenPrec: 0
})
