// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specializeIdentifier} from "./specialize.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$hQVQPOOO%mQPO'#ClO%tQPO'#ChO%|QPO'#C_O*pQPO'#CqO*wQPO'#CtOOQO'#Cu'#CuOOQO'#Cv'#CvOOQO'#Cw'#CwOOQO'#Cy'#CyOOQO'#C_'#C_OOQO'#C{'#C{QVQPOOOOQO,59W,59WO+OQPO,59WOOQO,59S,59SO%wQPO,59SOOQO,59Y,59YOOQO,59],59]O+VQPO,59]OOQO,59`,59`O+^QPO,59`OOQO-E6y-E6yOOQO1G.r1G.rOOQO1G.n1G.nOOQO1G.w1G.wOOQO1G.z1G.z",
  stateData: "+r~O!xOS~OPVOSYOTYOUYOVYOWYOXYOYYOZYO]RO_POaXOdSOgTOlWOnXOqUOrUOsUOtUOuUOvUOwUOxUOyUOzUO{UO|UO}UO!OUO!PUO!QUO!RUO!SUO!TUO!UUO!VUO!WUO!XUO!YQO!ZUO![UO!]UO!^UO!_UO!`UO!aUO!bUO!cUO!dUO!eUO!fUO!gUO!hUO!iUO!jUO!kUO!lUO!mUO!nUO!oUO!pUO!qUO!rUO!sUO!tUO!uUO!vUO~O^]O~PVO]`O_PO~OaaOPRXSRXTRXURXVRXWRXXRXYRXZRX]RX_RXdRXgRXlRXnRXpRXqRXrRXsRXtRXuRXvRXwRXxRXyRXzRX{RX|RX}RX!ORX!PRX!QRX!RRX!SRX!TRX!URX!VRX!WRX!XRX!YRX!ZRX![RX!]RX!^RX!_RX!`RX!aRX!bRX!cRX!dRX!eRX!fRX!gRX!hRX!iRX!jRX!kRX!lRX!mRX!nRX!oRX!pRX!qRX!rRX!sRX!tRX!uRX!vRX^RXcRXfRX~OcbO~PVOfdO~PVO^gO~PVOciO~PVOfjO~PVOSTUVWXYZ]lnX~",
  goto: "!ypPPPqPPPPPPPP{PPP!VP{PP{PP{{{{P{P!gaZOPST[^ceaYOPST[^ce`YOPST[^ceQ_QRh`Q[OQ^PQcSQeTXf[^ce",
  nodeNames: "⚠ BuiltinTypeName SourceFile Element ContainerDocComment DocComment LineComment LineString String Char Number Builtin FunctionDeclaration Identifier ) ( Parenthesized : Label } { Block ] [ Bracketed Keyword BuiltinType Operator OperatorToken Punctuation PunctuationToken",
  maxTerm: 86,
  nodeProps: [
    ["openedBy", 14,"(",19,"{",22,"["],
    ["closedBy", 15,")",20,"}",23,"]"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "3|~RuXY#fYZ#f]^#fpq#fqr#wrs$Uuv#wvw%ewx%pxy'Pyz'Uz{'Z{|'l|}'}}!O(S!O!P(b!P!Q(r!Q!R+e!R![-l![!]0s!]!^'}!^!_0x!_!`1T!`!a1`!a!b$P!b!c1k!c!}2Y!}#O2k#O#P2p#P#Q3b#Q#R#w#R#S2Y#T#o2Y#o#p3g#p#q3l#q#r3w#r#s$P~#kS!x~XY#fYZ#f]^#fpq#f~#|Pl~!_!`$P~$UOl~~$ZXW~OY$UZ]$U^r$Urs$vs#O$U#O#P${#P;'S$U;'S;=`%_<%lO$U~${OW~~%OTOY$UZ]$U^;'S$U;'S;=`%_<%lO$U~%bP;=`<%l$U~%jQl~vw$P!_!`$P~%uXX~OY%pZ]%p^w%pwx&bx#O%p#O#P&g#P;'S%p;'S;=`&y<%lO%p~&gOX~~&jTOY%pZ]%p^;'S%p;'S;=`&y<%lO%p~&|P;=`<%l%p~'UO_~~'ZO^~~'`Sl~uv#wz{$P!_!`$P#p#q#w~'qSl~uv#w{|$P!_!`$P#p#q#w~(SOn~~(XRl~uv#w!_!`$P#p#q#w~(gPl~!O!P(j~(oPl~!O!P$P~(wQl~!P!Q(}!_!`$P~)SXU~OY)oZ])o^q)oqr*Zr!P)o!P!Q*w!Q;'S)o;'S;=`*T<%lO)o~)tTU~OY)oZ])o^;'S)o;'S;=`*T<%lO)o~*WP;=`<%l)o~*bTS~U~OY*ZZ]*Z^;'S*Z;'S;=`*q<%lO*Z~*tP;=`<%l*Z~+OTT~U~OY*wZ]*w^;'S*w;'S;=`+_<%lO*w~+bP;=`<%l*w~+jZY~!O!P,]!Q![-l!d!e.Q!g!h,w!q!r.l!z!{/Q#R#S-l#U#V.Q#X#Y,w#c#d.l#l#m/Q~,`Q!Q![,f#R#S,f~,kSY~!Q![,f!g!h,w#R#S,f#X#Y,w~,zS{|-W}!O-W!Q![-a#R#S-a~-ZQ!Q![-a#R#S-a~-fQY~!Q![-a#R#S-a~-qTY~!O!P,]!Q![-l!g!h,w#R#S-l#X#Y,w~.TR!Q!R.^!R!S.^#R#S.^~.cRY~!Q!R.^!R!S.^#R#S.^~.oQ!Q!Y.u#R#S.u~.zQY~!Q!Y.u#R#S.u~/TS!Q![/a!c!i/a#R#S/a#T#Z/a~/fVY~!O!P/{!Q![/a!c!i/a!r!s,w#R#S/a#T#Z/a#d#e,w~0OS!Q![0[!c!i0[#R#S0[#T#Z0[~0aUY~!Q![0[!c!i0[!r!s,w#R#S0[#T#Z0[#d#e,w~0xOa~~0}Ql~!^!_#w!_!`$P~1YQl~!_!`$P!`!a$P~1eQl~!_!`$P!`!a#w~1nR!c!}1w#R#S1w#T#o1w~1|SZ~!Q![1w!c!}1w#R#S1w#T#o1w~2_S]~!Q![2Y!c!}2Y#R#S2Y#T#o2Y~2pOg~~2sP#O#P2v~2{TV~OY2vZ]2v^;'S2v;'S;=`3[<%lO2v~3_P;=`<%l2v~3gOf~~3lOd~~3qQl~!_!`$P#p#q$P~3|Oc~",
  tokenizers: [0],
  topRules: {"SourceFile":[0,2]},
  specialized: [{term: 13, get: (value, stack) => (specializeIdentifier(value, stack) << 1), external: specializeIdentifier}],
  tokenPrec: 481
})
