// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%WQ]QPOOOOQO'#Cd'#CdOtQPO'#CgO|QPO'#CnOOQO'#Cu'#CuOOQO'#Co'#CoQ]QPOOOOQO'#Ci'#CiO!TQPO'#ChO!YQPO'#CwOOQO,59R,59RO!bQPO,59RO!gQPO'#CxOOQO,59Y,59YO!oQPO,59YOOQO-E6m-E6mO]QPO,59SO!tQPO,59cO!|QPO,59cOOQO1G.m1G.mO#UQPO,59dO#]QPO,59dOOQO1G.t1G.tOOQO1G.n1G.nOOQO,59[,59[O#eQPO1G.}OOQO-E6n-E6nOOQO,59],59]O#mQPO1G/OOOQO-E6o-E6oPwQPO'#CpP]QPO'#Cq",
  stateData: "#t~OhOSPOSQOS~OSSOTSOUSOVSOYQOaROjPO~OXYOjVO~O`]O~P]O^`O~O_aOXkX~OXcO~O_dO`lX~O`fO~OjVOXka~O_iOXka~O`la~P]O_lO`la~OjVOXki~O`li~P]O",
  goto: "#OmPPPPPPPPnPPnw!PPPPPn!V!]!cPPP!iP!x!{_SORU`dloQXQVhainXWQainQUOR_UQbXRjbQe[RmeSTOUQ[RQg`VkdloRZQR^R",
  nodeNames: "⚠ LineComment BlockComment JsonText True False Null Number String } { Object Property PropertyName : , ] [ Array",
  maxTerm: 28,
  nodeProps: [
    ["isolate", -2,8,13,""],
    ["openedBy", 9,"{",16,"["],
    ["closedBy", 10,"}",17,"]"]
  ],
  skippedNodes: [0,1,2],
  repeatNodeCount: 3,
  tokenData: "+R~RbXY!ZYZ!Z]^!Zpq!Zrs!l|}%U}!O%Z!P!Q'T!Q!R%d!R![&r![!](y!}#O)O#P#Q)T#Y#Z)Y#b#c)w#h#i*`#o#p*w#q#r*|~!`Sh~XY!ZYZ!Z]^!Zpq!Z~!oWpq!lqr!lrs#Xs#O!l#O#P#^#P;'S!l;'S;=`%O<%lO!l~#^Oj~~#aXrs!l!P!Q!l#O#P!l#U#V!l#Y#Z!l#b#c!l#f#g!l#h#i!l#i#j#|~$PR!Q![$Y!c!i$Y#T#Z$Y~$]R!Q![$f!c!i$f#T#Z$f~$iR!Q![$r!c!i$r#T#Z$r~$uR!Q![!l!c!i!l#T#Z!l~%RP;=`<%l!l~%ZO_~~%^Q!Q!R%d!R![&r~%iRV~!O!P%r!g!h&W#X#Y&W~%uP!Q![%x~%}RV~!Q![%x!g!h&W#X#Y&W~&ZR{|&d}!O&d!Q![&j~&gP!Q![&j~&oPV~!Q![&j~&wSV~!O!P%r!Q![&r!g!h&W#X#Y&W~'WQz{'^!P!Q(_~'aTOz'^z{'p{;'S'^;'S;=`(X<%lO'^~'sTO!P'^!P!Q(S!Q;'S'^;'S;=`(X<%lO'^~(XOQ~~([P;=`<%l'^~(dTP~OY(_Z](_^;'S(_;'S;=`(s<%lO(_~(vP;=`<%l(_~)OO^~~)TOa~~)YO`~~)]P#T#U)`~)cP#`#a)f~)iP#g#h)l~)oP#X#Y)r~)wOT~~)zP#i#j)}~*QP#`#a*T~*WP#`#a*Z~*`OU~~*cP#f#g*f~*iP#i#j*l~*oP#X#Y*r~*wOS~~*|OY~~+ROX~",
  tokenizers: [0],
  topRules: {"JsonText":[0,3]},
  tokenPrec: 0
})
